# Generated by Django 4.2.6 on 2023-10-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Nombre')),
                ('año_nacimiento', models.SmallIntegerField(verbose_name='Año de nacimiento')),
                ('año_defuncion', models.SmallIntegerField(verbose_name='Año de defunción')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Editorial')),
                ('año', models.SmallIntegerField(verbose_name='Año de lanzamiento')),
                ('historia', models.TextField(verbose_name='Historia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Género')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Libro')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Malo'), (2, 'Mediocre'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')])),
                ('portada', models.ImageField(blank=True, null=True, upload_to='libros', verbose_name='Portada')),
                ('año', models.SmallIntegerField(verbose_name='Año de lanzamiento')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('autor', models.ManyToManyField(to='libros_app.autor', verbose_name='Autores')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_app.editorial', verbose_name='Editorial')),
                ('generos', models.ManyToManyField(to='libros_app.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libro',
            },
        ),
    ]
