# Generated by Django 4.2.6 on 2023-10-29 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='año_defuncion',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='año_nacimiento',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='año',
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_defuncion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
