# Generated by Django 4.2.6 on 2023-10-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0002_remove_autor_año_defuncion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='año',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='editorial',
            name='ano',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Año de fundacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='ano_publicacion',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Año de publicacion'),
        ),
    ]
