# Generated by Django 4.2.6 on 2023-10-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0003_alter_libro_options_remove_editorial_año_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_defuncion',
        ),
    ]
