# Generated by Django 4.2.6 on 2023-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0004_remove_autor_fecha_defuncion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
