# Generated by Django 4.2.6 on 2023-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0006_remove_libro_description_libro_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores', verbose_name='Autor'),
        ),
    ]
