# Generated by Django 4.2.6 on 2023-10-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros_app', '0007_autor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='editoriales', verbose_name='Autor'),
        ),
    ]
